import { NextRequest } from 'next/server';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';
import type { TranscriptSummary } from '@/actions/transcript';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Body = {
  summary: TranscriptSummary;
  meta: {
    ticker: string;
    companyName: string;
    quarter: string;
    callDate: string;
  };
};

type Heading =
  | typeof HeadingLevel.HEADING_1
  | typeof HeadingLevel.HEADING_2
  | typeof HeadingLevel.HEADING_3;

function H(text: string, level: Heading) {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true })],
  });
}

function P(text: string, opts: { italics?: boolean; bold?: boolean; size?: number } = {}) {
  return new Paragraph({
    spacing: { after: 120 },
    children: [
      new TextRun({
        text,
        italics: opts.italics,
        bold: opts.bold,
        size: opts.size,
      }),
    ],
  });
}

function Bullet(text: string) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 60 },
    children: [new TextRun({ text })],
  });
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as Body;
    const { summary, meta } = body;
    if (!summary || !meta) {
      return new Response('Missing summary or meta', { status: 400 });
    }

    const children = [
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { after: 240 },
        children: [
          new TextRun({
            text: `${meta.companyName} (${meta.ticker})`,
            bold: true,
            size: 32,
          }),
        ],
      }),
      P(`${meta.quarter} Earnings Briefing${meta.callDate ? ` · Call: ${meta.callDate}` : ''}`, {
        italics: true,
      }),

      P(summary.greeting),
      P(summary.stockMoveContext, { italics: true }),

      H('Headline', HeadingLevel.HEADING_2),
      P(summary.headline, { bold: true }),

      ...summary.categories.flatMap((c) => {
        if (c.notDiscussed) {
          return [
            H(c.category, HeadingLevel.HEADING_3),
            P('Not discussed this quarter.', { italics: true }),
          ];
        }
        return [
          H(c.category, HeadingLevel.HEADING_3),
          ...c.bullets.map(Bullet),
          P(`Bottom line: ${c.bottomLine}`, { italics: true, bold: true }),
        ];
      }),
    ];

    if (summary.execHighlights.length > 0) {
      children.push(H('Executive highlights', HeadingLevel.HEADING_2));
      for (const e of summary.execHighlights) {
        children.push(
          new Paragraph({
            spacing: { after: 80 },
            indent: { left: 360 },
            children: [
              new TextRun({ text: `"${e.quote}"`, italics: true }),
              new TextRun({ text: `  — ${e.exec}`, bold: true }),
              new TextRun({ text: ` (${e.context})`, color: '666666' }),
            ],
          })
        );
      }
    }

    if (summary.qaThemes.length > 0) {
      children.push(H('Q&A themes', HeadingLevel.HEADING_2));
      for (const q of summary.qaThemes) children.push(Bullet(q));
    }

    if (summary.sentimentArc) {
      children.push(H('Sentiment arc', HeadingLevel.HEADING_2));
      children.push(P(summary.sentimentArc, { italics: true }));
    }

    children.push(
      new Paragraph({
        spacing: { before: 360 },
        border: { top: { color: 'BBBBBB', size: 6, style: 'single' } },
        children: [
          new TextRun({
            text: `— ${meta.companyName} IR briefing · auto-generated by Ticker on Recursiv`,
            size: 16,
            color: '888888',
          }),
        ],
      })
    );

    const doc = new Document({
      creator: 'Ticker on Recursiv',
      title: `${meta.ticker} ${meta.quarter} Earnings Briefing`,
      description: `Earnings briefing for ${meta.companyName} (${meta.ticker}) ${meta.quarter}`,
      styles: {
        default: {
          document: { run: { font: 'Georgia', size: 22 } },
        },
      },
      sections: [{ children }],
    });

    const buffer = await Packer.toBuffer(doc);
    const safeQuarter = meta.quarter.replace(/[^a-z0-9-]+/gi, '-');
    const filename = `${meta.ticker}-${safeQuarter}-briefing.docx`;

    return new Response(new Uint8Array(buffer), {
      headers: {
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    return new Response(
      `Failed to build .docx: ${err instanceof Error ? err.message : 'unknown error'}`,
      { status: 500 }
    );
  }
}
