import { NextRequest } from 'next/server';
import {
  buildPdf,
  bullet,
  divider,
  footer,
  h1,
  h2,
  h3,
  p,
  pdfResponse,
  quote as pdfQuote,
} from '@/lib/pdf-helpers';
import type { TranscriptSummary } from '@/actions/transcript';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Body = {
  summary: TranscriptSummary;
  meta: {
    ticker: string;
    companyName: string;
    quarter: string;
    callDate: string;
  };
};

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as Body;
    const { summary, meta } = body;
    if (!summary || !meta) return new Response('Missing summary or meta', { status: 400 });

    const safeQuarter = meta.quarter.replace(/[^a-z0-9-]+/gi, '-');
    const result = await buildPdf(`${meta.ticker}-${safeQuarter}-briefing.pdf`, (doc) => {
      // Title block
      doc.font('Helvetica-Bold').fontSize(22).fillColor('#0f172a').text(`${meta.companyName} (${meta.ticker})`);
      doc
        .moveDown(0.2)
        .font('Helvetica-Oblique')
        .fontSize(11)
        .fillColor('#64748b')
        .text(`${meta.quarter} Earnings Briefing${meta.callDate ? ` · Call: ${meta.callDate}` : ''}`);
      doc.moveDown(0.8);
      divider(doc);

      // Greeting + stock context
      p(doc, summary.greeting);
      p(doc, summary.stockMoveContext, { italic: true, color: '#64748b' });

      // Headline
      h2(doc, 'Headline');
      p(doc, summary.headline, { color: '#0f172a' });

      // Categories
      for (const c of summary.categories) {
        h3(doc, c.category);
        if (c.notDiscussed) {
          p(doc, 'Not discussed this quarter.', { italic: true, color: '#94a3b8' });
        } else {
          for (const b of c.bullets) bullet(doc, b);
          p(doc, `Bottom line: ${c.bottomLine}`, { italic: true, color: '#047857' });
        }
      }

      // Exec highlights
      if (summary.execHighlights.length > 0) {
        h2(doc, 'Executive highlights');
        for (const e of summary.execHighlights) {
          pdfQuote(doc, e.quote, `${e.exec} · ${e.context}`);
        }
      }

      // Q&A themes
      if (summary.qaThemes.length > 0) {
        h2(doc, 'Q&A themes');
        for (const q of summary.qaThemes) bullet(doc, q);
      }

      // Sentiment arc
      if (summary.sentimentArc) {
        h2(doc, 'Sentiment arc');
        p(doc, summary.sentimentArc, { italic: true });
      }

      footer(
        doc,
        `— ${meta.companyName} IR briefing · auto-generated by Ticker on Recursiv`
      );
    });

    return pdfResponse(result);
  } catch (err) {
    return new Response(
      `Failed to build PDF: ${err instanceof Error ? err.message : 'unknown'}`,
      { status: 500 }
    );
  }
}
