import { NextRequest } from 'next/server';
import {
  buildPdf,
  bullet,
  divider,
  footer,
  h1,
  h2,
  h3,
  p,
  pdfResponse,
} from '@/lib/pdf-helpers';
import type { EarningsScript } from '@/actions/script';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Body = {
  script: EarningsScript;
  meta: { ticker: string; companyName: string; quarter: string };
};

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as Body;
    const { script, meta } = body;
    if (!script || !meta) return new Response('Missing script or meta', { status: 400 });

    const safeQuarter = meta.quarter.replace(/[^a-z0-9-]+/gi, '-');
    const result = await buildPdf(`${meta.ticker}-${safeQuarter}-script.pdf`, (doc) => {
      doc.font('Helvetica-Bold').fontSize(22).fillColor('#0f172a').text(`${meta.companyName} (${meta.ticker})`);
      doc
        .moveDown(0.2)
        .font('Helvetica-Oblique')
        .fontSize(11)
        .fillColor('#64748b')
        .text(
          `${meta.quarter} Earnings Call Script · Est. ${script.timing.ceoEstimatedMinutes}min CEO / ${script.timing.cfoEstimatedMinutes}min CFO`
        );
      doc.moveDown(0.8);
      divider(doc);

      h1(doc, 'CEO Prepared Remarks');
      for (const s of script.prepared_remarks.ceo) {
        h3(doc, s.section);
        for (const para of s.content.split(/\n+/).filter(Boolean)) {
          p(doc, para);
        }
      }

      h1(doc, 'CFO Prepared Remarks');
      for (const s of script.prepared_remarks.cfo) {
        h3(doc, s.section);
        for (const para of s.content.split(/\n+/).filter(Boolean)) {
          p(doc, para);
        }
      }

      if (script.speakerNotes && script.speakerNotes.length > 0) {
        h2(doc, 'Speaker Notes');
        for (const n of script.speakerNotes) bullet(doc, n);
      }

      footer(
        doc,
        `— ${meta.companyName} earnings script · auto-generated by Ticker on Recursiv`
      );
    });

    return pdfResponse(result);
  } catch (err) {
    return new Response(
      `Failed: ${err instanceof Error ? err.message : 'unknown'}`,
      { status: 500 }
    );
  }
}
