'use client';

import { useState, useTransition } from 'react';
import {
  summarizeTranscript,
  type Attachment,
  type TranscriptSummary,
} from '@/actions/transcript';
import { LastMileDelivery } from '@/components/last-mile';
import {
  AgentCard,
  ErrorBox,
  Field,
  LoadingBox,
  PoweredBy,
  PrimaryButton,
} from '@/components/agent-ui';
import {
  DistributionListEditor,
  DistributionListPill,
} from '@/components/distribution-list';
import { cn } from '@/lib/utils';

type Sample = {
  ticker: string;
  label: string;
  quarter: string;
  callDate: string;
  text: string;
};

export function TranscriptWorkbench({
  symbol,
  companyName,
  categories,
  samples,
}: {
  symbol: string;
  companyName: string;
  categories: string[];
  samples: Sample[];
}) {
  const defaultSample = samples[0];
  const [transcript, setTranscript] = useState(defaultSample?.text ?? '');
  const [quarter, setQuarter] = useState(defaultSample?.quarter ?? '');
  const [callDate, setCallDate] = useState(defaultSample?.callDate ?? '');
  const [transcriptType, setTranscriptType] = useState<'corrected' | 'realtime'>('corrected');
  const [result, setResult] = useState<TranscriptSummary | null>(null);
  const [meta, setMeta] = useState<{
    quarter: string;
    callDate: string;
    categoriesUsed: string[];
    attachments: Attachment[];
    stockMove?: { last: number; changePct: number; formatted: string };
  } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const [showRecipients, setShowRecipients] = useState(false);
  const [downloading, setDownloading] = useState(false);

  function loadSample(s: Sample) {
    setTranscript(s.text);
    setQuarter(s.quarter);
    setCallDate(s.callDate);
    setResult(null);
    setError(null);
  }

  function submit() {
    setError(null);
    setResult(null);
    startTransition(async () => {
      const res = await summarizeTranscript({
        symbol,
        transcript,
        quarter,
        callDate,
      });
      if (!res.ok) {
        setError(res.error);
        return;
      }
      setResult(res.summary);
      setMeta({
        quarter: res.meta.quarter,
        callDate: res.meta.callDate,
        categoriesUsed: res.meta.categoriesUsed,
        attachments: res.meta.attachments ?? [],
        stockMove: res.meta.stockMove,
      });
    });
  }

  function copyEmail() {
    if (!result) return;
    const lines = [
      result.greeting,
      '',
      result.stockMoveContext,
      '',
      `Headline: ${result.headline}`,
      '',
      ...result.categories.flatMap((c) =>
        c.notDiscussed
          ? [`${c.category}`, '· Not discussed this quarter', '']
          : [
              `${c.category}`,
              ...c.bullets.map((b) => `· ${b}`),
              `Bottom line: ${c.bottomLine}`,
              '',
            ]
      ),
      result.execHighlights.length > 0 ? 'Executive highlights:' : '',
      ...result.execHighlights.map((e) => `· ${e.exec}: "${e.quote}" (${e.context})`),
      '',
      result.qaThemes.length > 0 ? 'Q&A themes:' : '',
      ...result.qaThemes.map((q) => `· ${q}`),
      '',
      result.sentimentArc ? `Sentiment arc: ${result.sentimentArc}` : '',
      '',
      '---',
      `Generated by Ticker · ${symbol} · ${meta?.quarter ?? quarter}`,
    ].filter(Boolean);
    navigator.clipboard.writeText(lines.join('\n'));
  }

  async function downloadDoc(format: 'docx' | 'pdf') {
    if (!result || !meta) return;
    setDownloading(true);
    try {
      const res = await fetch(`/api/transcript/${format}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          summary: result,
          meta: { ticker: symbol, companyName, quarter: meta.quarter, callDate: meta.callDate },
        }),
      });
      if (!res.ok) {
        const text = await res.text();
        setError(`${format.toUpperCase()} export failed: ${text}`);
        return;
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const safeQuarter = (meta.quarter || 'briefing').replace(/[^a-z0-9-]+/gi, '-');
      a.download = `${symbol}-${safeQuarter}-briefing.${format}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } finally {
      setDownloading(false);
    }
  }

  return (
    <div className="space-y-6">
      <AgentCard>
        {categories.length === 0 ? (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
            No focus categories defined for {symbol}. Add them on the company overview before
            running.
          </div>
        ) : (
          <div className="rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] p-3">
            <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--muted-soft)] mb-2">
              Output will be organized by these {categories.length} categories
            </div>
            <div className="flex flex-wrap gap-1.5">
              {categories.map((c, i) => (
                <span
                  key={c}
                  className="inline-flex items-center gap-1 rounded-full bg-[var(--accent-soft)] text-[var(--accent-ink)] px-2.5 py-0.5 text-xs"
                >
                  <span className="mono text-[10px] text-[var(--accent-ink)]/60">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  {c}
                </span>
              ))}
            </div>
          </div>
        )}

        <div className="grid gap-3 sm:grid-cols-3">
          <Field label="Quarter">
            <input
              value={quarter}
              onChange={(e) => setQuarter(e.target.value)}
              placeholder="Q1 2026"
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] px-3 h-10 text-sm outline-none focus:border-accent/60 focus:ring-4 focus:ring-accent/10 transition-all"
            />
          </Field>
          <Field label="Call date">
            <input
              type="date"
              value={callDate}
              onChange={(e) => setCallDate(e.target.value)}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] px-3 h-10 text-sm mono outline-none focus:border-accent/60 focus:ring-4 focus:ring-accent/10 transition-all"
            />
          </Field>
          <Field label="Transcript type">
            <div className="grid grid-cols-2 gap-1.5 h-10">
              <button
                onClick={() => setTranscriptType('corrected')}
                className={cn(
                  'rounded-lg border text-xs transition-colors',
                  transcriptType === 'corrected'
                    ? 'border-[var(--accent-ink)] bg-[var(--accent-soft)] text-[var(--accent-ink)] font-medium'
                    : 'border-[var(--border)] text-[var(--fg-soft)] hover:border-[var(--muted-soft)]'
                )}
              >
                Corrected
              </button>
              <button
                onClick={() => setTranscriptType('realtime')}
                className={cn(
                  'rounded-lg border text-xs transition-colors',
                  transcriptType === 'realtime'
                    ? 'border-[var(--accent-ink)] bg-[var(--accent-soft)] text-[var(--accent-ink)] font-medium'
                    : 'border-[var(--border)] text-[var(--fg-soft)] hover:border-[var(--muted-soft)]'
                )}
              >
                Real-time
              </button>
            </div>
          </Field>
        </div>

        <Field
          label="Transcript text"
          hint={`${transcript.length.toLocaleString()} chars · paste full transcript`}
        >
          <textarea
            value={transcript}
            onChange={(e) => setTranscript(e.target.value)}
            placeholder="Paste the corrected earnings call transcript here..."
            className="w-full h-72 rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] px-3 py-2 text-sm outline-none focus:border-accent/60 focus:ring-4 focus:ring-accent/10 transition-all resize-y font-sans leading-relaxed"
          />
          {samples.length > 0 && (
            <div className="mt-2 flex items-center gap-2 text-[11px] text-[var(--muted)]">
              <span>Or load:</span>
              {samples.map((s) => (
                <button
                  key={s.label}
                  onClick={() => loadSample(s)}
                  className="rounded-md border border-[var(--border)] bg-[var(--bg-raised)] px-2 py-0.5 hover:border-accent/40 hover:text-[var(--accent-ink)] transition-colors"
                >
                  {s.label}
                </button>
              ))}
            </div>
          )}
        </Field>

        <PrimaryButton
          onClick={submit}
          disabled={pending || transcript.trim().length < 500 || !quarter.trim()}
        >
          {pending ? 'Summarizing' : 'Summarize transcript'}
        </PrimaryButton>

        <PoweredBy text="Earnings Transcript Summarizer agent · organized by your categories" />
      </AgentCard>

      {error && <ErrorBox error={error} />}
      {pending && (
        <LoadingBox label="Earnings Transcript Summarizer is reading the call and organizing by your categories" />
      )}

      {result && meta && (
        <>
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <h2 className="text-sm font-medium text-[var(--fg-soft)]">Briefing email</h2>
            <div className="flex items-center gap-2 flex-wrap">
              <DistributionListPill symbol={symbol} onClick={() => setShowRecipients(true)} />
              <button
                onClick={() => downloadDoc('docx')}
                disabled={downloading}
                className="inline-flex items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] px-3 h-8 text-xs text-[var(--fg-soft)] hover:border-accent/40 hover:text-[var(--accent-ink)] disabled:opacity-50 transition-colors"
              >
                <DocIcon />
                Word
              </button>
              <button
                onClick={() => downloadDoc('pdf')}
                disabled={downloading}
                className="inline-flex items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-raised)] px-3 h-8 text-xs text-[var(--fg-soft)] hover:border-accent/40 hover:text-[var(--accent-ink)] disabled:opacity-50 transition-colors"
              >
                <PdfIcon />
                {downloading ? 'Building...' : 'PDF'}
              </button>
              <button
                onClick={copyEmail}
                className="text-xs text-[var(--muted)] hover:text-[var(--accent-ink)]"
              >
                Copy all
              </button>
            </div>
          </div>

          <article className="rounded-2xl border border-[var(--border)] bg-[var(--card)] shadow-sm p-6 space-y-5">
            <div className="space-y-2">
              <p className="text-sm text-[var(--fg)] leading-relaxed">{result.greeting}</p>
              <p className="text-sm text-[var(--muted)] italic">{result.stockMoveContext}</p>
            </div>

            <div className="rounded-xl bg-[var(--accent-soft)] p-4">
              <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--accent-ink)]/70 mb-1">
                Headline
              </div>
              <p className="text-base font-medium text-[var(--fg)] leading-snug">
                {result.headline}
              </p>
            </div>

            <div className="space-y-4 pt-2">
              {result.categories.map((c) => (
                <CategoryBlock key={c.category} cat={c} />
              ))}
            </div>

            {result.execHighlights.length > 0 && (
              <div className="border-t border-[var(--border)] pt-4">
                <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--muted-soft)] mb-2">
                  Executive highlights
                </div>
                <div className="space-y-2">
                  {result.execHighlights.map((e, i) => (
                    <blockquote
                      key={i}
                      className="border-l-2 border-[var(--accent-ink)]/30 pl-3 text-sm"
                    >
                      <div className="italic text-[var(--fg-soft)]">&ldquo;{e.quote}&rdquo;</div>
                      <div className="mt-0.5 text-xs text-[var(--muted)]">
                        {e.exec} · {e.context}
                      </div>
                    </blockquote>
                  ))}
                </div>
              </div>
            )}

            {result.qaThemes.length > 0 && (
              <div className="border-t border-[var(--border)] pt-4">
                <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--muted-soft)] mb-2">
                  Q&A themes
                </div>
                <ul className="space-y-1 text-sm text-[var(--fg-soft)]">
                  {result.qaThemes.map((q, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="text-[var(--muted-soft)]">·</span>
                      <span>{q}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {result.sentimentArc && (
              <div className="border-t border-[var(--border)] pt-4">
                <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--muted-soft)] mb-1">
                  Sentiment arc
                </div>
                <p className="text-sm text-[var(--fg-soft)] italic">{result.sentimentArc}</p>
              </div>
            )}

            <div className="border-t border-[var(--border)] pt-4 text-xs text-[var(--muted)]">
              <div className="mb-2 mono">— {companyName} IR briefing · auto-generated</div>
              <div className="space-y-1">
                {meta.attachments.length > 0 ? (
                  meta.attachments.map((a) => (
                    <a
                      key={a.url}
                      href={a.url}
                      target="_blank"
                      rel="noopener"
                      className="block rounded-md border border-[var(--border)] bg-[var(--bg-raised)] px-3 py-2 text-[11px] text-[var(--fg-soft)] hover:border-accent/40 hover:text-[var(--accent-ink)] transition-colors"
                    >
                      <span className="mr-1">📎</span>
                      {a.label}{' '}
                      <span className="text-[var(--muted-soft)] mono">
                        · {a.type === 'presentation' ? 'PRESENTATION' : a.type === 'press_release' ? 'PRESS RELEASE' : 'TRANSCRIPT'}
                      </span>
                    </a>
                  ))
                ) : (
                  <div className="rounded-md border border-dashed border-[var(--border)] bg-[var(--bg-raised)]/60 px-3 py-2 text-[11px] text-[var(--muted-soft)]">
                    📎 No 8-K exhibits found for the most recent filing.
                  </div>
                )}
              </div>
            </div>
          </article>

          <LastMileDelivery onCopy={copyEmail} />
        </>
      )}

      {showRecipients && (
        <DistributionListEditor symbol={symbol} onClose={() => setShowRecipients(false)} />
      )}
    </div>
  );
}

function CategoryBlock({
  cat,
}: {
  cat: {
    category: string;
    bullets: string[];
    bottomLine: string;
    notDiscussed: boolean;
  };
}) {
  if (cat.notDiscussed) {
    return (
      <div className="rounded-lg border border-dashed border-[var(--border)] p-3">
        <div className="flex items-center justify-between">
          <div className="text-sm font-medium text-[var(--fg-soft)]">{cat.category}</div>
          <span className="text-[10px] mono uppercase tracking-wider text-[var(--muted-soft)]">
            Not discussed
          </span>
        </div>
      </div>
    );
  }
  return (
    <div className="rounded-lg border border-[var(--border)] p-4 bg-[var(--bg-raised)]/40">
      <div className="text-sm font-semibold text-[var(--fg)] mb-2">{cat.category}</div>
      <ul className="space-y-1 text-sm text-[var(--fg-soft)]">
        {cat.bullets.map((b, i) => (
          <li key={i} className="flex gap-2 leading-relaxed">
            <span className="text-[var(--accent-ink)]/60 shrink-0">·</span>
            <span>{b}</span>
          </li>
        ))}
      </ul>
      <div className="mt-3 pt-3 border-t border-[var(--border)] text-xs text-[var(--accent-ink)] italic">
        Bottom line: {cat.bottomLine}
      </div>
    </div>
  );
}

function DocIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" className="h-3.5 w-3.5">
      <path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" />
      <path d="M14 3v5h5" />
      <path d="M9 13h6M9 17h4" />
    </svg>
  );
}

function PdfIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" className="h-3.5 w-3.5">
      <path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" />
      <path d="M14 3v5h5" />
      <path d="M9 14h1.5a1.5 1.5 0 0 1 0 3H9v-3Zm0 0v4m4-4h2m-2 0v4m0-2h1.5m2-2h2m-2 0v4" />
    </svg>
  );
}
